# ~/.config/starship.toml

continuation_prompt = "[â–¶   ](bright-black)"

right_format = "$all"
format       = "$character"
add_newline  = false

[character]
success_symbol = "[ï‘„](bold green)"
error_symbol   = "[ï—](bold red)"
vicmd_symbol   = "[î˜«](bold yellow)"

[directory]
style = "white"

[sudo]
style = "bold red"
# symbol = "#"
format = "[$symbol]($style)"
disabled = false

[custom.tab]
description = "The current tab in the tab terminal multiplexer"
command = "tab --starship"
when = "tab --starship"
shell = ["sh"]
format = "[$output]($style) "
style = "bold blue"

[git_branch]
format = "[$symbol$branch]($style)"
style = "bright-white"
symbol = "ğŸŒ± "

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

